#!/bin/bash

# If TMPDIR is not set or is not a valid directory, use ~/Downloads
if [ -z "$TMPDIR" ] || [ ! -d "$TMPDIR" ]; then
    TMPDIR="$(xdg-user-dir DOWNLOAD)"
fi

# Always ensure TMPDIR has /thunderbird.tmp appended
export TMPDIR="$TMPDIR/thunderbird.tmp"

exec "$@"
